CREATE TABLE stored_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_provider VARCHAR(30) NOT NULL DEFAULT 'local',
    category VARCHAR(30) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    uploaded_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_stored_files_user
        FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id)
);

CREATE TABLE file_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stored_file_id BIGINT NOT NULL,
    linked_entity_type VARCHAR(30) NOT NULL,
    linked_entity_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_file_links_stored_file
        FOREIGN KEY (stored_file_id) REFERENCES stored_files(id)
);
