CREATE TABLE user_role_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    role_name VARCHAR(30) NOT NULL,
    role_state VARCHAR(20) NOT NULL,
    region_id VARCHAR(100),
    reason VARCHAR(500),
    changed_by_user_id BIGINT,
    changed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_role_states_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_states_changed_by_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE role_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(100) NOT NULL,
    role_name VARCHAR(30) NOT NULL,
    role_assignable BOOLEAN NOT NULL DEFAULT TRUE,
    default_host_permission BOOLEAN NOT NULL DEFAULT FALSE,
    default_partner_permission BOOLEAN NOT NULL DEFAULT FALSE,
    individual_host_permission_grant_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    individual_partner_permission_grant_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    admin_approval_required_for_pause BOOLEAN NOT NULL DEFAULT FALSE,
    admin_approval_required_for_withdrawal BOOLEAN NOT NULL DEFAULT FALSE,
    admin_approval_required_for_role_restore BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_role_policies_region_role UNIQUE (region_id, role_name)
);

CREATE TABLE permission_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(100) NOT NULL,
    target_user_id BIGINT NOT NULL,
    permission_name VARCHAR(30) NOT NULL,
    rule_state VARCHAR(20) NOT NULL,
    effective_from DATE,
    effective_to DATE,
    granted_at TIMESTAMP,
    granted_by_user_id BIGINT,
    grant_reason VARCHAR(500),
    suspended_at TIMESTAMP,
    suspended_by_user_id BIGINT,
    suspension_reason VARCHAR(500),
    resumed_at TIMESTAMP,
    resumed_by_user_id BIGINT,
    resume_reason VARCHAR(500),
    revoked_at TIMESTAMP,
    revoked_by_user_id BIGINT,
    revoke_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_permission_rules_scope UNIQUE (region_id, target_user_id, permission_name),
    CONSTRAINT fk_permission_rules_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_rules_granted_by
        FOREIGN KEY (granted_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_rules_suspended_by
        FOREIGN KEY (suspended_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_rules_resumed_by
        FOREIGN KEY (resumed_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_rules_revoked_by
        FOREIGN KEY (revoked_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE partner_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    partner_user_id BIGINT NOT NULL,
    assignment_status VARCHAR(20) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    effective_from DATE,
    effective_to DATE,
    ended_at TIMESTAMP,
    assigned_by_user_id BIGINT,
    assignment_reason VARCHAR(500),
    paused_at TIMESTAMP,
    paused_by_user_id BIGINT,
    pause_reason VARCHAR(500),
    resumed_at TIMESTAMP,
    resumed_by_user_id BIGINT,
    resume_reason VARCHAR(500),
    ended_by_user_id BIGINT,
    end_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_partner_assignments_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_assignments_partner_user
        FOREIGN KEY (partner_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_assignments_assigned_by
        FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_assignments_paused_by
        FOREIGN KEY (paused_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_assignments_resumed_by
        FOREIGN KEY (resumed_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_partner_assignments_ended_by
        FOREIGN KEY (ended_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE permission_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(100),
    target_user_id BIGINT NOT NULL,
    changed_object_type VARCHAR(30) NOT NULL,
    changed_object_name VARCHAR(100) NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    before_value CLOB,
    after_value CLOB,
    changed_by_user_id BIGINT NOT NULL,
    reason VARCHAR(500),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_permission_change_logs_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_change_logs_changed_by
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_user_id BIGINT NOT NULL,
    viewer_context VARCHAR(30) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT NOT NULL,
    view_reason VARCHAR(500),
    viewed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_access_logs_viewer_user
        FOREIGN KEY (viewer_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE region_scoped_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(100) NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_region_scoped_settings_scope UNIQUE (region_id, setting_key)
);
