CREATE TABLE support_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_user_id BIGINT NOT NULL,
    region_id VARCHAR(100),
    note_type VARCHAR(30) NOT NULL,
    note_status VARCHAR(20) NOT NULL,
    body CLOB NOT NULL,
    care_points CLOB,
    visit_companions VARCHAR(500),
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_reason VARCHAR(500),
    hidden_by_user_id BIGINT,
    hidden_at TIMESTAMP,
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_support_notes_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notes_hidden_by
        FOREIGN KEY (hidden_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notes_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notes_updated_by
        FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE support_note_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_note_id BIGINT NOT NULL,
    reported_by_user_id BIGINT NOT NULL,
    report_note VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_support_note_reports_note
        FOREIGN KEY (support_note_id) REFERENCES support_notes(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_note_reports_reported_by
        FOREIGN KEY (reported_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);
