CREATE TABLE map_record_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_record_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_map_record_bookmark UNIQUE (map_record_id, user_id),
    CONSTRAINT fk_map_record_bookmarks_record
        FOREIGN KEY (map_record_id) REFERENCES map_records(id),
    CONSTRAINT fk_map_record_bookmarks_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
