CREATE TABLE point_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    region_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    source_mode VARCHAR(20) NOT NULL,
    points INT NOT NULL,
    event_reason VARCHAR(255) NOT NULL,
    related_target_type VARCHAR(80),
    related_target_id BIGINT,
    awarded_by_user_id BIGINT,
    awarded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_point_events_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_point_events_user_awarded_at
    ON point_events(user_id, awarded_at DESC);

CREATE INDEX idx_point_events_region_event
    ON point_events(region_id, event_type, awarded_at DESC);

CREATE INDEX idx_point_events_related_target
    ON point_events(related_target_type, related_target_id);
