INSERT INTO users (
    id,
    email,
    password_hash,
    nickname,
    name,
    name_kana,
    birthday,
    gender,
    phone_number,
    address,
    sms_verified,
    additional_verification_status,
    created_at,
    updated_at
) VALUES
    (101, 'ito@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '伊藤さん', '伊藤さん', 'いとうさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0101', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (102, 'hasegawa@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '長谷川さん', '長谷川さん', 'はせがわさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0102', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (103, 'hosyo@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '宝生さん', '宝生さん', 'ほうしょうさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0103', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (104, 'todo@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '東堂さん', '東堂さん', 'とうどうさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0104', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (108, 'rikyu@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '利休さん', '利休さん', 'りきゅうさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0108', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (109, 'rurikawa@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '瑠璃川さん', '瑠璃川さん', 'るりかわさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0109', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (110, 'watanabe@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '渡辺さん', '渡辺さん', 'わたなべさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0110', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (111, 'watanabe-collab@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '渡辺さん・瑠璃川さん', '渡辺さん・瑠璃川さん', 'わたなべるりかわ', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0111', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (112, 'yoshino@example.com', '$2a$10$0N5mBXj8pdodQXemdQeztuc9FwwyfErcy4T5wPF7w3NG5HodZs1AS', '吉野さん', '吉野さん', 'よしのさん', DATE '1990-01-01', 'NO_ANSWER', '090-0000-0112', 'Catalog Seed', TRUE, 'UNREQUESTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, role_name, created_at) VALUES
    (101, 'LOCAL', CURRENT_TIMESTAMP),
    (102, 'LOCAL', CURRENT_TIMESTAMP),
    (103, 'LOCAL', CURRENT_TIMESTAMP),
    (104, 'LOCAL', CURRENT_TIMESTAMP),
    (108, 'LOCAL', CURRENT_TIMESTAMP),
    (109, 'LOCAL', CURRENT_TIMESTAMP),
    (110, 'LOCAL', CURRENT_TIMESTAMP),
    (111, 'LOCAL', CURRENT_TIMESTAMP),
    (112, 'LOCAL', CURRENT_TIMESTAMP);

INSERT INTO user_profiles (
    user_id,
    bio,
    icon_path,
    region,
    interest_region,
    visit_history,
    care_note,
    with_children,
    food_note,
    relation_note,
    age_range,
    created_at,
    updated_at
) VALUES
    (101, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (102, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (103, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (104, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (108, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (109, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (110, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (111, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (112, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO contact_preferences (
    user_id,
    receive_operation_notice,
    receive_security_notice,
    receive_bridge_contact,
    receive_local_contact,
    receive_email_notice,
    receive_sms_notice,
    created_at,
    updated_at
) VALUES
    (101, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (102, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (103, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (104, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (108, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (109, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (110, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (111, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (112, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO proposals (
    id,
    proposal_type,
    bridge_user_id,
    host_user_id,
    title,
    summary,
    body,
    duration_minutes,
    location_name,
    status,
    visibility_scope,
    cover_image_path,
    created_at,
    updated_at,
    deleted_at
) VALUES
    (1001, 'GATE', NULL, 101, 'gate-ito-walk', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1002, 'GATE', NULL, 101, 'gate-ito-flower', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1003, 'GATE', NULL, 102, 'gate-hasegawa', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1004, 'GATE', NULL, 103, 'gate-hosyo', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1005, 'GATE', NULL, 104, 'gate-todo-walk', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1006, 'GATE', NULL, 104, 'gate-todo-leather', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1007, 'GATE', NULL, 108, 'gate-rikyu-cafe', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1008, 'GATE', NULL, 108, 'gate-rikyu-walk', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1009, 'GATE', NULL, 109, 'gate-rurikawa-farm', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1010, 'GATE', NULL, 109, 'gate-rurikawa-walk', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1011, 'GATE', NULL, 110, 'gate-watanabe-water', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1012, 'GATE', NULL, 110, 'gate-watanabe-stream', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (1013, 'GATE', NULL, 112, 'gate-yoshino-bike', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (22001, 'OKATTE', NULL, 101, 'okatte-ito', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23002, 'OKATTE', NULL, 102, 'okatte-hasegawa-grape', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23003, 'OKATTE', NULL, 102, 'okatte-hasegawa-chrysanthemum', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23004, 'OKATTE', NULL, 103, 'okatte-hosyo-anago', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23005, 'OKATTE', NULL, 103, 'okatte-hosyo-scenery', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23006, 'OKATTE', NULL, 104, 'okatte-todo', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23007, 'OKATTE', NULL, 108, 'okatte-rikyu', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23008, 'OKATTE', NULL, 110, 'okatte-watanabe-stream', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23009, 'OKATTE', NULL, 110, 'okatte-watanabe-sea', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23010, 'OKATTE', NULL, 111, 'okatte-watanabe-imoni', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23011, 'OKATTE', NULL, 111, 'okatte-watanabe-imoni-help', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
    (23012, 'OKATTE', NULL, 112, 'okatte-yoshino-farm', NULL, NULL, NULL, NULL, 'published', 'public', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
