CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_name VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    bio VARCHAR(1000),
    icon_path VARCHAR(255),
    region VARCHAR(100),
    interest_region VARCHAR(100),
    visit_history VARCHAR(1000),
    care_note VARCHAR(1000),
    with_children VARCHAR(30),
    food_note VARCHAR(500),
    relation_note VARCHAR(500),
    age_range VARCHAR(30),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE contact_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    receive_operation_notice BOOLEAN NOT NULL DEFAULT TRUE,
    receive_security_notice BOOLEAN NOT NULL DEFAULT TRUE,
    receive_bridge_contact BOOLEAN NOT NULL DEFAULT TRUE,
    receive_local_contact BOOLEAN NOT NULL DEFAULT FALSE,
    receive_email_notice BOOLEAN NOT NULL DEFAULT TRUE,
    receive_sms_notice BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_contact_preferences_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
