CREATE TABLE map_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(4000),
    visibility VARCHAR(20) NOT NULL DEFAULT 'private',
    location_name VARCHAR(255),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    location_precision_level VARCHAR(20) NOT NULL DEFAULT 'area',
    is_draft BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    visibility_updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_map_records_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE map_record_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_record_id BIGINT NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_map_record_images_record
        FOREIGN KEY (map_record_id) REFERENCES map_records(id)
);

CREATE TABLE map_record_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_record_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_map_record_comments_record
        FOREIGN KEY (map_record_id) REFERENCES map_records(id),
    CONSTRAINT fk_map_record_comments_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
