CREATE TABLE story_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(4000) NOT NULL,
    summary VARCHAR(500),
    cover_image_path VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'published',
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_story_posts_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE story_post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_story_post_comments_post
        FOREIGN KEY (story_post_id) REFERENCES story_posts(id),
    CONSTRAINT fk_story_post_comments_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE story_post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_story_post_reaction UNIQUE (story_post_id, user_id, reaction_type),
    CONSTRAINT fk_story_post_reactions_post
        FOREIGN KEY (story_post_id) REFERENCES story_posts(id),
    CONSTRAINT fk_story_post_reactions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
