CREATE TABLE proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_type VARCHAR(30) NOT NULL,
    bridge_user_id BIGINT,
    host_user_id BIGINT,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(500),
    body VARCHAR(4000),
    duration_minutes INT,
    location_name VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'published',
    visibility_scope VARCHAR(20) NOT NULL DEFAULT 'public',
    cover_image_path VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_proposals_bridge_user
        FOREIGN KEY (bridge_user_id) REFERENCES users(id),
    CONSTRAINT fk_proposals_host_user
        FOREIGN KEY (host_user_id) REFERENCES users(id)
);

CREATE TABLE proposal_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_proposal_tags_proposal
        FOREIGN KEY (proposal_id) REFERENCES proposals(id)
);

CREATE TABLE proposal_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    application_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    latest_message_preview VARCHAR(500),
    latest_message_at TIMESTAMP,
    related_thread_id BIGINT,
    requires_additional_verification BOOLEAN NOT NULL DEFAULT FALSE,
    applied_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_proposal_applications_proposal
        FOREIGN KEY (proposal_id) REFERENCES proposals(id),
    CONSTRAINT fk_proposal_applications_user
        FOREIGN KEY (applicant_user_id) REFERENCES users(id)
);

CREATE TABLE proposal_application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_application_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    changed_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_status_history_application
        FOREIGN KEY (proposal_application_id) REFERENCES proposal_applications(id),
    CONSTRAINT fk_status_history_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);
