CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(500),
    related_entity_type VARCHAR(30),
    related_entity_id BIGINT,
    related_url VARCHAR(255),
    sender_name VARCHAR(100),
    sender_role VARCHAR(30),
    preview_text VARCHAR(255),
    severity VARCHAR(20) NOT NULL DEFAULT 'normal',
    action_label VARCHAR(50),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notification_delivery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    delivery_channel VARCHAR(20) NOT NULL,
    delivery_status VARCHAR(20) NOT NULL,
    delivered_at TIMESTAMP,
    failure_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_delivery_logs_notification
        FOREIGN KEY (notification_id) REFERENCES notifications(id)
);
