CREATE TABLE chat_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    counterpart_id BIGINT,
    counterpart_role VARCHAR(30) NOT NULL,
    related_entity_type VARCHAR(30),
    related_entity_id BIGINT,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    unread_count INT NOT NULL DEFAULT 0,
    requires_attention BOOLEAN NOT NULL DEFAULT FALSE,
    related_url VARCHAR(255),
    latest_message_preview VARCHAR(500),
    latest_message_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_chat_threads_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_chat_threads_counterpart
        FOREIGN KEY (counterpart_id) REFERENCES users(id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    sender_id BIGINT,
    sender_role VARCHAR(30) NOT NULL,
    body VARCHAR(4000) NOT NULL,
    is_system_message BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_chat_messages_thread
        FOREIGN KEY (thread_id) REFERENCES chat_threads(id),
    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_id) REFERENCES users(id)
);
