CREATE TABLE map_record_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_record_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_map_record_reaction UNIQUE (map_record_id, user_id, reaction_type),
    CONSTRAINT fk_map_record_reactions_record
        FOREIGN KEY (map_record_id) REFERENCES map_records(id),
    CONSTRAINT fk_map_record_reactions_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
