CREATE TABLE support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    request_type VARCHAR(30) NOT NULL,
    related_feature VARCHAR(50),
    target_reference VARCHAR(255),
    body VARCHAR(4000) NOT NULL,
    reply_preference VARCHAR(20) NOT NULL DEFAULT 'optional',
    status VARCHAR(30) NOT NULL DEFAULT 'received',
    handled_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_support_requests_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_support_requests_handler
        FOREIGN KEY (handled_by_user_id) REFERENCES users(id)
);

CREATE TABLE support_request_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_request_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    changed_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_support_request_status_history_request
        FOREIGN KEY (support_request_id) REFERENCES support_requests(id),
    CONSTRAINT fk_support_request_status_history_user
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
);
